POST http://localhost:8080/petlover/register
Content-Type: application/json

{
   "email": "nanami@gmail.com",
   "name": "maria elena",
   "password": "qwert"
}
###
POST http://localhost:8080/petlover/authentication
Content-Type: application/json

{
  "email": "elenavf@gmail.com",
  "password": "qwert"
}
###

POST http://localhost:8080/petservice/registerService
Content-Type: application/json

{
  "name": "PetCare",
  "descrip":"Aplicacion para adquirir un petService",
  "schedule": "24-7",
  "address": "All over the world",
  "location": "In you heart"
}
###