POST http://localhost:8080/petlover/register
Content-Type: application/json

{
   "email": "elena@gmail.com",
   "name": "elena",
   "password": "qwert"
}
###
POST http://localhost:8080/petlover/authentication
Content-Type: application/json

{
  "email": "elena@gmail.com",
  "password": "qwert"
}
###